# Generated by Django 5.0.4 on 2024-04-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalissuecommentbody",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="historicalissuecommentbody",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="issuecommentbody",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="issuecommentbody",
            name="updated_at",
        ),
    ]
