# Generated by Django 5.0.4 on 2024-04-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalissue",
            name="number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="issue",
            name="number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name="issue",
            constraint=models.UniqueConstraint(fields=("number", "repository"), name="unique_issue"),
        ),
    ]
