# Generated by Django 5.0.4 on 2024-04-17 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
        ("github", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRepositoryFollow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="followers", to="github.repository"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories_followed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User repository follow",
                "verbose_name_plural": "User repository follows",
            },
        ),
        migrations.AddConstraint(
            model_name="userrepositoryfollow",
            constraint=models.UniqueConstraint(fields=("user", "repository"), name="unique_user_repository_follow"),
        ),
    ]
