# Generated by Django 5.0.4 on 2024-04-19 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrepositoryfollow",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userrepositoryfollow",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
